In [3]:
import pandas as pd

In [7]:
oil = {}
oil['coconut'] = pd.read_csv('../Datasets/Oils/archive/cleaned/cocount.csv')
oil['cottonseed'] = pd.read_csv('../Datasets/Oils/archive/cleaned/cottonseed.csv')
oil['olive'] = pd.read_csv('../Datasets/Oils/archive/cleaned/olive.csv')
oil['palm'] = pd.read_csv('../Datasets/Oils/archive/cleaned/palm.csv')
oil['palm_kernel'] = pd.read_csv('../Datasets/Oils/archive/cleaned/palm_kernel.csv')
oil['peanut'] = pd.read_csv('../Datasets/Oils/archive/cleaned/peanut.csv')
oil['rapeseed'] = pd.read_csv('../Datasets/Oils/archive/cleaned/rapeseeed.csv')
oil['soybean'] = pd.read_csv('../Datasets/Oils/archive/cleaned/soybean.csv')
oil['sunflowerseed'] = pd.read_csv('../Datasets/Oils/archive/cleaned/sunflowerseed.csv')

In [29]:
palm = pd.read_csv('../Datasets/Oils/archive/cleaned/palm.csv')
trees = pd.read_csv('../Datasets/Deforestation/Country tree cover loss.csv').groupby('country').agg({'area_ha': 'sum'})

In [26]:
# for key, value in oil.items():
#     print(key)
#     print(value.info())
#     print()

oil['palm']['Domestic Consumption'].describe()
# oil['palm']['Area Harvested'].max()

count     5820.000000
mean       251.178007
std        973.933203
min          0.000000
25%          0.000000
50%         23.000000
75%        128.000000
max      20350.000000
Name: Domestic Consumption, dtype: float64

In [30]:
palm = palm.drop(palm[palm['Year'] < 2000].index).groupby('Country').agg({'Production': 'sum'})

In [33]:
palm.head(60)

                              Production
Country
Afghanistan                          0.0
Algeria                              0.0
Angola                            1225.0
Australia                            0.0
Austria                              0.0
Bangladesh                           0.0
Belgium-Luxembourg                   0.0
Benin                             1249.0
Brazil                            8124.0
Burma                                0.0
Cameroon                          7272.0
Canada                               0.0
China                                0.0
Colombia                         26446.0
Congo (Kinshasa)                  5591.0
Costa Rica                        5264.0
Cote d'Ivoire                     9556.0
Denmark                              0.0
Djibouti                             0.0
Dominican Republic                 969.0
EU-15                                0.0
Ecuador                          10499.0
Egypt                                0.0
El Salvador                          0.0
Ethiopia                             0.0
European Union                       0.0
Finland                              0.0
Former Czechoslovakia                0.0
Former Yugoslavia                    0.0
France                               0.0
Germany, Federal Republic of         0.0
Ghana                             5471.0
Greece                               0.0
Guatemala                        10597.0
Guinea                            1200.0
Haiti                                0.0
Honduras                          9177.0
Hong Kong                            0.0
India                             3537.0
Indonesia                       658290.0
Iran                                 0.0
Iraq                                 0.0
Ireland                              0.0
Italy                                0.0
Japan                                0.0
Jordan                               0.0
Kenya                                0.0
Korea, North                         0.0
Korea, South                         0.0
Kuwait                               0.0
Liberia                           1029.0
Madagascar                           0.0
Malaysia                        414416.0
Mauritania                           0.0
Mexico                            2620.0
Mozambique                           0.0
Netherlands                          0.0
New Zealand                          0.0
Nigeria                          23476.0
Norway                               0.0

In [34]:
pd.read_csv('../Datasets/Oils/archive/cleaned/palm.csv').groupby('Country').agg({'Production': 'sum'}).head(60)

                              Production
Country
Afghanistan                          0.0
Algeria                              0.0
Angola                            2674.0
Australia                            0.0
Austria                              0.0
Bangladesh                           0.0
Belgium-Luxembourg                   0.0
Benin                             2442.0
Brazil                            9414.0
Burma                                0.0
Cameroon                         10357.0
Canada                               0.0
China                              311.0
Colombia                         31877.0
Congo (Kinshasa)                 11011.0
Costa Rica                        6923.0
Cote d'Ivoire                    15884.0
Denmark                              0.0
Djibouti                             0.0
Dominican Republic                1126.0
EU-15                                0.0
Ecuador                          13420.0
Egypt                                0.0
El Salvador                          0.0
Ethiopia                             0.0
European Union                       0.0
Finland                              0.0
Former Czechoslovakia                0.0
Former Yugoslavia                    0.0
France                               0.0
Germany, Federal Republic of         0.0
Ghana                             6686.0
Greece                               0.0
Guatemala                        10990.0
Guinea                            2480.0
Haiti                                0.0
Honduras                         10649.0
Hong Kong                            0.0
India                             3737.0
Indonesia                       721653.0
Iran                                 0.0
Iraq                                 0.0
Ireland                              0.0
Italy                                0.0
Japan                                0.0
Jordan                               0.0
Kenya                                0.0
Korea, North                         0.0
Korea, South                         0.0
Kuwait                               0.0
Liberia                           2032.0
Madagascar                           0.0
Malaysia                        552873.0
Mauritania                           0.0
Mexico                            2674.0
Mozambique                           0.0
Netherlands                          0.0
New Zealand                          0.0
Nigeria                          43015.0
Norway                               0.0